// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface AudioStreamOpenedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.AudioStreamOpened)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string source_id = 1;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string source_id = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string source_kind = 3;</code>
   * @return The sourceKind.
   */
  java.lang.String getSourceKind();
  /**
   * <code>string source_kind = 3;</code>
   * @return The bytes for sourceKind.
   */
  com.google.protobuf.ByteString
      getSourceKindBytes();

  /**
   * <code>bytes channel_id = 4;</code>
   * @return The channelId.
   */
  com.google.protobuf.ByteString getChannelId();

  /**
   * <code>.listensphere.protocol.v1.StartStream stream = 5;</code>
   * @return Whether the stream field is set.
   */
  boolean hasStream();
  /**
   * <code>.listensphere.protocol.v1.StartStream stream = 5;</code>
   * @return The stream.
   */
  io.listensphere.protocol.v1.StartStream getStream();

  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 6;</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 6;</code>
   * @return The error.
   */
  io.listensphere.protocol.v1.ErrorCode getError();
}
