// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface CloseAudioStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.CloseAudioStream)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>fixed32 stream_id = 1;</code>
   * @return The streamId.
   */
  int getStreamId();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
