// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface DeviceIdentityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.DeviceIdentity)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes device_id = 1;</code>
   * @return The deviceId.
   */
  com.google.protobuf.ByteString getDeviceId();

  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string platform = 3;</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <code>string platform = 3;</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();

  /**
   * <code>uint64 capabilities = 4;</code>
   * @return The capabilities.
   */
  long getCapabilities();

  /**
   * <code>bytes certificate_fingerprint = 5;</code>
   * @return The certificateFingerprint.
   */
  com.google.protobuf.ByteString getCertificateFingerprint();
}
