// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.DeviceIdentity}
 */
public  final class DeviceIdentity extends
    com.google.protobuf.GeneratedMessageLite<
        DeviceIdentity, DeviceIdentity.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.DeviceIdentity)
    DeviceIdentityOrBuilder {
  private DeviceIdentity() {
    deviceId_ = com.google.protobuf.ByteString.EMPTY;
    displayName_ = "";
    platform_ = "";
    certificateFingerprint_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int DEVICE_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString deviceId_;
  /**
   * <code>bytes device_id = 1;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>bytes device_id = 1;</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceId_ = value;
  }
  /**
   * <code>bytes device_id = 1;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 2;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    displayName_ = value;
  }
  /**
   * <code>string display_name = 2;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int PLATFORM_FIELD_NUMBER = 3;
  private java.lang.String platform_;
  /**
   * <code>string platform = 3;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    return platform_;
  }
  /**
   * <code>string platform = 3;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(platform_);
  }
  /**
   * <code>string platform = 3;</code>
   * @param value The platform to set.
   */
  private void setPlatform(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    platform_ = value;
  }
  /**
   * <code>string platform = 3;</code>
   */
  private void clearPlatform() {

    platform_ = getDefaultInstance().getPlatform();
  }
  /**
   * <code>string platform = 3;</code>
   * @param value The bytes for platform to set.
   */
  private void setPlatformBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    platform_ = value.toStringUtf8();

  }

  public static final int CAPABILITIES_FIELD_NUMBER = 4;
  private long capabilities_;
  /**
   * <code>uint64 capabilities = 4;</code>
   * @return The capabilities.
   */
  @java.lang.Override
  public long getCapabilities() {
    return capabilities_;
  }
  /**
   * <code>uint64 capabilities = 4;</code>
   * @param value The capabilities to set.
   */
  private void setCapabilities(long value) {
    
    capabilities_ = value;
  }
  /**
   * <code>uint64 capabilities = 4;</code>
   */
  private void clearCapabilities() {

    capabilities_ = 0L;
  }

  public static final int CERTIFICATE_FINGERPRINT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString certificateFingerprint_;
  /**
   * <code>bytes certificate_fingerprint = 5;</code>
   * @return The certificateFingerprint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCertificateFingerprint() {
    return certificateFingerprint_;
  }
  /**
   * <code>bytes certificate_fingerprint = 5;</code>
   * @param value The certificateFingerprint to set.
   */
  private void setCertificateFingerprint(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    certificateFingerprint_ = value;
  }
  /**
   * <code>bytes certificate_fingerprint = 5;</code>
   */
  private void clearCertificateFingerprint() {

    certificateFingerprint_ = getDefaultInstance().getCertificateFingerprint();
  }

  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.DeviceIdentity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.DeviceIdentity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.DeviceIdentity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.DeviceIdentity prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.DeviceIdentity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.DeviceIdentity, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.DeviceIdentity)
      io.listensphere.protocol.v1.DeviceIdentityOrBuilder {
    // Construct using io.listensphere.protocol.v1.DeviceIdentity.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes device_id = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>bytes device_id = 1;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>bytes device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }

    /**
     * <code>string display_name = 2;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 2;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>string platform = 3;</code>
     * @return The platform.
     */
    @java.lang.Override
    public java.lang.String getPlatform() {
      return instance.getPlatform();
    }
    /**
     * <code>string platform = 3;</code>
     * @return The bytes for platform.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      return instance.getPlatformBytes();
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      copyOnWrite();
      instance.setPlatform(value);
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      copyOnWrite();
      instance.clearPlatform();
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPlatformBytes(value);
      return this;
    }

    /**
     * <code>uint64 capabilities = 4;</code>
     * @return The capabilities.
     */
    @java.lang.Override
    public long getCapabilities() {
      return instance.getCapabilities();
    }
    /**
     * <code>uint64 capabilities = 4;</code>
     * @param value The capabilities to set.
     * @return This builder for chaining.
     */
    public Builder setCapabilities(long value) {
      copyOnWrite();
      instance.setCapabilities(value);
      return this;
    }
    /**
     * <code>uint64 capabilities = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapabilities() {
      copyOnWrite();
      instance.clearCapabilities();
      return this;
    }

    /**
     * <code>bytes certificate_fingerprint = 5;</code>
     * @return The certificateFingerprint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCertificateFingerprint() {
      return instance.getCertificateFingerprint();
    }
    /**
     * <code>bytes certificate_fingerprint = 5;</code>
     * @param value The certificateFingerprint to set.
     * @return This builder for chaining.
     */
    public Builder setCertificateFingerprint(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCertificateFingerprint(value);
      return this;
    }
    /**
     * <code>bytes certificate_fingerprint = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCertificateFingerprint() {
      copyOnWrite();
      instance.clearCertificateFingerprint();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.DeviceIdentity)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.DeviceIdentity();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "deviceId_",
            "displayName_",
            "platform_",
            "capabilities_",
            "certificateFingerprint_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\n\u0002\u0208" +
              "\u0003\u0208\u0004\u0003\u0005\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.DeviceIdentity> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.DeviceIdentity.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.DeviceIdentity>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.DeviceIdentity)
  private static final io.listensphere.protocol.v1.DeviceIdentity DEFAULT_INSTANCE;
  static {
    DeviceIdentity defaultInstance = new DeviceIdentity();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeviceIdentity.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.DeviceIdentity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeviceIdentity> PARSER;

  public static com.google.protobuf.Parser<DeviceIdentity> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

