// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.Disconnect}
 */
public  final class Disconnect extends
    com.google.protobuf.GeneratedMessageLite<
        Disconnect, Disconnect.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.Disconnect)
    DisconnectOrBuilder {
  private Disconnect() {
    reason_ = "";
  }
  public static final int ERROR_FIELD_NUMBER = 1;
  private int error_;
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @return The enum numeric value on the wire for error.
   */
  @java.lang.Override
  public int getErrorValue() {
    return error_;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.ErrorCode getError() {
    io.listensphere.protocol.v1.ErrorCode result = io.listensphere.protocol.v1.ErrorCode.forNumber(error_);
    return result == null ? io.listensphere.protocol.v1.ErrorCode.UNRECOGNIZED : result;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @param value The enum numeric value on the wire for error to set.
   */
  private void setErrorValue(int value) {
      error_ = value;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @param value The error to set.
   */
  private void setError(io.listensphere.protocol.v1.ErrorCode value) {
    error_ = value.getNumber();

  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   */
  private void clearError() {

    error_ = 0;
  }

  public static final int REASON_FIELD_NUMBER = 2;
  private java.lang.String reason_;
  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 2;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 2;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 2;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.Disconnect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.Disconnect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Disconnect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.Disconnect prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.Disconnect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.Disconnect, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.Disconnect)
      io.listensphere.protocol.v1.DisconnectOrBuilder {
    // Construct using io.listensphere.protocol.v1.Disconnect.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
     * @return The enum numeric value on the wire for error.
     */
    @java.lang.Override
    public int getErrorValue() {
      return instance.getErrorValue();
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorValue(int value) {
      copyOnWrite();
      instance.setErrorValue(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
     * @return The error.
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.ErrorCode getError() {
      return instance.getError();
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
     * @param value The enum numeric value on the wire for error to set.
     * @return This builder for chaining.
     */
    public Builder setError(io.listensphere.protocol.v1.ErrorCode value) {
      copyOnWrite();
      instance.setError(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      copyOnWrite();
      instance.clearError();
      return this;
    }

    /**
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 2;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 2;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.Disconnect)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.Disconnect();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "error_",
            "reason_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.Disconnect> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.Disconnect.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.Disconnect>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.Disconnect)
  private static final io.listensphere.protocol.v1.Disconnect DEFAULT_INSTANCE;
  static {
    Disconnect defaultInstance = new Disconnect();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Disconnect.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.Disconnect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Disconnect> PARSER;

  public static com.google.protobuf.Parser<Disconnect> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

