// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface DisconnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.Disconnect)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 1;</code>
   * @return The error.
   */
  io.listensphere.protocol.v1.ErrorCode getError();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
