// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.Envelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   * @return The version.
   */
  io.listensphere.protocol.v1.ProtocolVersion getVersion();

  /**
   * <code>fixed64 request_id = 2;</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   * @return Whether the pairRequest field is set.
   */
  boolean hasPairRequest();
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   * @return The pairRequest.
   */
  io.listensphere.protocol.v1.PairRequest getPairRequest();

  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   * @return Whether the pairResponse field is set.
   */
  boolean hasPairResponse();
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   * @return The pairResponse.
   */
  io.listensphere.protocol.v1.PairResponse getPairResponse();

  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   * @return The heartbeat.
   */
  io.listensphere.protocol.v1.Heartbeat getHeartbeat();

  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   * @return Whether the startStream field is set.
   */
  boolean hasStartStream();
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   * @return The startStream.
   */
  io.listensphere.protocol.v1.StartStream getStartStream();

  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   * @return Whether the stopStream field is set.
   */
  boolean hasStopStream();
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   * @return The stopStream.
   */
  io.listensphere.protocol.v1.StopStream getStopStream();

  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   * @return Whether the helloRequest field is set.
   */
  boolean hasHelloRequest();
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   * @return The helloRequest.
   */
  io.listensphere.protocol.v1.HelloRequest getHelloRequest();

  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   * @return Whether the helloResponse field is set.
   */
  boolean hasHelloResponse();
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   * @return The helloResponse.
   */
  io.listensphere.protocol.v1.HelloResponse getHelloResponse();

  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   * @return Whether the heartbeatAck field is set.
   */
  boolean hasHeartbeatAck();
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   * @return The heartbeatAck.
   */
  io.listensphere.protocol.v1.HeartbeatAck getHeartbeatAck();

  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   * @return Whether the disconnect field is set.
   */
  boolean hasDisconnect();
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   * @return The disconnect.
   */
  io.listensphere.protocol.v1.Disconnect getDisconnect();

  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   * @return Whether the openAudioStream field is set.
   */
  boolean hasOpenAudioStream();
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   * @return The openAudioStream.
   */
  io.listensphere.protocol.v1.OpenAudioStream getOpenAudioStream();

  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   * @return Whether the audioStreamOpened field is set.
   */
  boolean hasAudioStreamOpened();
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   * @return The audioStreamOpened.
   */
  io.listensphere.protocol.v1.AudioStreamOpened getAudioStreamOpened();

  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   * @return Whether the closeAudioStream field is set.
   */
  boolean hasCloseAudioStream();
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   * @return The closeAudioStream.
   */
  io.listensphere.protocol.v1.CloseAudioStream getCloseAudioStream();

  public io.listensphere.protocol.v1.Envelope.PayloadCase getPayloadCase();
}
