// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.Envelope}
 */
public  final class Envelope extends
    com.google.protobuf.GeneratedMessageLite<
        Envelope, Envelope.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.Envelope)
    EnvelopeOrBuilder {
  private Envelope() {
  }
  private int bitField0_;
  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase {
    PAIR_REQUEST(10),
    PAIR_RESPONSE(11),
    HEARTBEAT(12),
    START_STREAM(13),
    STOP_STREAM(14),
    HELLO_REQUEST(15),
    HELLO_RESPONSE(16),
    HEARTBEAT_ACK(17),
    DISCONNECT(18),
    OPEN_AUDIO_STREAM(19),
    AUDIO_STREAM_OPENED(20),
    CLOSE_AUDIO_STREAM(21),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 10: return PAIR_REQUEST;
        case 11: return PAIR_RESPONSE;
        case 12: return HEARTBEAT;
        case 13: return START_STREAM;
        case 14: return STOP_STREAM;
        case 15: return HELLO_REQUEST;
        case 16: return HELLO_RESPONSE;
        case 17: return HEARTBEAT_ACK;
        case 18: return DISCONNECT;
        case 19: return OPEN_AUDIO_STREAM;
        case 20: return AUDIO_STREAM_OPENED;
        case 21: return CLOSE_AUDIO_STREAM;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  private void clearPayload() {
    payloadCase_ = 0;
    payload_ = null;
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private io.listensphere.protocol.v1.ProtocolVersion version_;
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.ProtocolVersion getVersion() {
    return version_ == null ? io.listensphere.protocol.v1.ProtocolVersion.getDefaultInstance() : version_;
  }
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   */
  private void setVersion(io.listensphere.protocol.v1.ProtocolVersion value) {
    value.getClass();
  version_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVersion(io.listensphere.protocol.v1.ProtocolVersion value) {
    value.getClass();
  if (version_ != null &&
        version_ != io.listensphere.protocol.v1.ProtocolVersion.getDefaultInstance()) {
      version_ =
        io.listensphere.protocol.v1.ProtocolVersion.newBuilder(version_).mergeFrom(value).buildPartial();
    } else {
      version_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
   */
  private void clearVersion() {  version_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 2;
  private long requestId_;
  /**
   * <code>fixed64 request_id = 2;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public long getRequestId() {
    return requestId_;
  }
  /**
   * <code>fixed64 request_id = 2;</code>
   * @param value The requestId to set.
   */
  private void setRequestId(long value) {
    
    requestId_ = value;
  }
  /**
   * <code>fixed64 request_id = 2;</code>
   */
  private void clearRequestId() {

    requestId_ = 0L;
  }

  public static final int PAIR_REQUEST_FIELD_NUMBER = 10;
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   */
  @java.lang.Override
  public boolean hasPairRequest() {
    return payloadCase_ == 10;
  }
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.PairRequest getPairRequest() {
    if (payloadCase_ == 10) {
       return (io.listensphere.protocol.v1.PairRequest) payload_;
    }
    return io.listensphere.protocol.v1.PairRequest.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   */
  private void setPairRequest(io.listensphere.protocol.v1.PairRequest value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 10;
  }
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   */
  private void mergePairRequest(io.listensphere.protocol.v1.PairRequest value) {
    value.getClass();
  if (payloadCase_ == 10 &&
        payload_ != io.listensphere.protocol.v1.PairRequest.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.PairRequest.newBuilder((io.listensphere.protocol.v1.PairRequest) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 10;
  }
  /**
   * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
   */
  private void clearPairRequest() {
    if (payloadCase_ == 10) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int PAIR_RESPONSE_FIELD_NUMBER = 11;
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   */
  @java.lang.Override
  public boolean hasPairResponse() {
    return payloadCase_ == 11;
  }
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.PairResponse getPairResponse() {
    if (payloadCase_ == 11) {
       return (io.listensphere.protocol.v1.PairResponse) payload_;
    }
    return io.listensphere.protocol.v1.PairResponse.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   */
  private void setPairResponse(io.listensphere.protocol.v1.PairResponse value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 11;
  }
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   */
  private void mergePairResponse(io.listensphere.protocol.v1.PairResponse value) {
    value.getClass();
  if (payloadCase_ == 11 &&
        payload_ != io.listensphere.protocol.v1.PairResponse.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.PairResponse.newBuilder((io.listensphere.protocol.v1.PairResponse) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 11;
  }
  /**
   * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
   */
  private void clearPairResponse() {
    if (payloadCase_ == 11) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 12;
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return payloadCase_ == 12;
  }
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.Heartbeat getHeartbeat() {
    if (payloadCase_ == 12) {
       return (io.listensphere.protocol.v1.Heartbeat) payload_;
    }
    return io.listensphere.protocol.v1.Heartbeat.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   */
  private void setHeartbeat(io.listensphere.protocol.v1.Heartbeat value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 12;
  }
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   */
  private void mergeHeartbeat(io.listensphere.protocol.v1.Heartbeat value) {
    value.getClass();
  if (payloadCase_ == 12 &&
        payload_ != io.listensphere.protocol.v1.Heartbeat.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.Heartbeat.newBuilder((io.listensphere.protocol.v1.Heartbeat) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 12;
  }
  /**
   * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
   */
  private void clearHeartbeat() {
    if (payloadCase_ == 12) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int START_STREAM_FIELD_NUMBER = 13;
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   */
  @java.lang.Override
  public boolean hasStartStream() {
    return payloadCase_ == 13;
  }
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.StartStream getStartStream() {
    if (payloadCase_ == 13) {
       return (io.listensphere.protocol.v1.StartStream) payload_;
    }
    return io.listensphere.protocol.v1.StartStream.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   */
  private void setStartStream(io.listensphere.protocol.v1.StartStream value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 13;
  }
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   */
  private void mergeStartStream(io.listensphere.protocol.v1.StartStream value) {
    value.getClass();
  if (payloadCase_ == 13 &&
        payload_ != io.listensphere.protocol.v1.StartStream.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.StartStream.newBuilder((io.listensphere.protocol.v1.StartStream) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 13;
  }
  /**
   * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
   */
  private void clearStartStream() {
    if (payloadCase_ == 13) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int STOP_STREAM_FIELD_NUMBER = 14;
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   */
  @java.lang.Override
  public boolean hasStopStream() {
    return payloadCase_ == 14;
  }
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.StopStream getStopStream() {
    if (payloadCase_ == 14) {
       return (io.listensphere.protocol.v1.StopStream) payload_;
    }
    return io.listensphere.protocol.v1.StopStream.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   */
  private void setStopStream(io.listensphere.protocol.v1.StopStream value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 14;
  }
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   */
  private void mergeStopStream(io.listensphere.protocol.v1.StopStream value) {
    value.getClass();
  if (payloadCase_ == 14 &&
        payload_ != io.listensphere.protocol.v1.StopStream.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.StopStream.newBuilder((io.listensphere.protocol.v1.StopStream) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 14;
  }
  /**
   * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
   */
  private void clearStopStream() {
    if (payloadCase_ == 14) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int HELLO_REQUEST_FIELD_NUMBER = 15;
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   */
  @java.lang.Override
  public boolean hasHelloRequest() {
    return payloadCase_ == 15;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.HelloRequest getHelloRequest() {
    if (payloadCase_ == 15) {
       return (io.listensphere.protocol.v1.HelloRequest) payload_;
    }
    return io.listensphere.protocol.v1.HelloRequest.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   */
  private void setHelloRequest(io.listensphere.protocol.v1.HelloRequest value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 15;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   */
  private void mergeHelloRequest(io.listensphere.protocol.v1.HelloRequest value) {
    value.getClass();
  if (payloadCase_ == 15 &&
        payload_ != io.listensphere.protocol.v1.HelloRequest.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.HelloRequest.newBuilder((io.listensphere.protocol.v1.HelloRequest) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 15;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
   */
  private void clearHelloRequest() {
    if (payloadCase_ == 15) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int HELLO_RESPONSE_FIELD_NUMBER = 16;
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   */
  @java.lang.Override
  public boolean hasHelloResponse() {
    return payloadCase_ == 16;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.HelloResponse getHelloResponse() {
    if (payloadCase_ == 16) {
       return (io.listensphere.protocol.v1.HelloResponse) payload_;
    }
    return io.listensphere.protocol.v1.HelloResponse.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   */
  private void setHelloResponse(io.listensphere.protocol.v1.HelloResponse value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 16;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   */
  private void mergeHelloResponse(io.listensphere.protocol.v1.HelloResponse value) {
    value.getClass();
  if (payloadCase_ == 16 &&
        payload_ != io.listensphere.protocol.v1.HelloResponse.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.HelloResponse.newBuilder((io.listensphere.protocol.v1.HelloResponse) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 16;
  }
  /**
   * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
   */
  private void clearHelloResponse() {
    if (payloadCase_ == 16) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int HEARTBEAT_ACK_FIELD_NUMBER = 17;
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   */
  @java.lang.Override
  public boolean hasHeartbeatAck() {
    return payloadCase_ == 17;
  }
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.HeartbeatAck getHeartbeatAck() {
    if (payloadCase_ == 17) {
       return (io.listensphere.protocol.v1.HeartbeatAck) payload_;
    }
    return io.listensphere.protocol.v1.HeartbeatAck.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   */
  private void setHeartbeatAck(io.listensphere.protocol.v1.HeartbeatAck value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 17;
  }
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   */
  private void mergeHeartbeatAck(io.listensphere.protocol.v1.HeartbeatAck value) {
    value.getClass();
  if (payloadCase_ == 17 &&
        payload_ != io.listensphere.protocol.v1.HeartbeatAck.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.HeartbeatAck.newBuilder((io.listensphere.protocol.v1.HeartbeatAck) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 17;
  }
  /**
   * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
   */
  private void clearHeartbeatAck() {
    if (payloadCase_ == 17) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int DISCONNECT_FIELD_NUMBER = 18;
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   */
  @java.lang.Override
  public boolean hasDisconnect() {
    return payloadCase_ == 18;
  }
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.Disconnect getDisconnect() {
    if (payloadCase_ == 18) {
       return (io.listensphere.protocol.v1.Disconnect) payload_;
    }
    return io.listensphere.protocol.v1.Disconnect.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   */
  private void setDisconnect(io.listensphere.protocol.v1.Disconnect value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 18;
  }
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   */
  private void mergeDisconnect(io.listensphere.protocol.v1.Disconnect value) {
    value.getClass();
  if (payloadCase_ == 18 &&
        payload_ != io.listensphere.protocol.v1.Disconnect.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.Disconnect.newBuilder((io.listensphere.protocol.v1.Disconnect) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 18;
  }
  /**
   * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
   */
  private void clearDisconnect() {
    if (payloadCase_ == 18) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int OPEN_AUDIO_STREAM_FIELD_NUMBER = 19;
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   */
  @java.lang.Override
  public boolean hasOpenAudioStream() {
    return payloadCase_ == 19;
  }
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.OpenAudioStream getOpenAudioStream() {
    if (payloadCase_ == 19) {
       return (io.listensphere.protocol.v1.OpenAudioStream) payload_;
    }
    return io.listensphere.protocol.v1.OpenAudioStream.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   */
  private void setOpenAudioStream(io.listensphere.protocol.v1.OpenAudioStream value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 19;
  }
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   */
  private void mergeOpenAudioStream(io.listensphere.protocol.v1.OpenAudioStream value) {
    value.getClass();
  if (payloadCase_ == 19 &&
        payload_ != io.listensphere.protocol.v1.OpenAudioStream.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.OpenAudioStream.newBuilder((io.listensphere.protocol.v1.OpenAudioStream) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 19;
  }
  /**
   * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
   */
  private void clearOpenAudioStream() {
    if (payloadCase_ == 19) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int AUDIO_STREAM_OPENED_FIELD_NUMBER = 20;
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   */
  @java.lang.Override
  public boolean hasAudioStreamOpened() {
    return payloadCase_ == 20;
  }
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.AudioStreamOpened getAudioStreamOpened() {
    if (payloadCase_ == 20) {
       return (io.listensphere.protocol.v1.AudioStreamOpened) payload_;
    }
    return io.listensphere.protocol.v1.AudioStreamOpened.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   */
  private void setAudioStreamOpened(io.listensphere.protocol.v1.AudioStreamOpened value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 20;
  }
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   */
  private void mergeAudioStreamOpened(io.listensphere.protocol.v1.AudioStreamOpened value) {
    value.getClass();
  if (payloadCase_ == 20 &&
        payload_ != io.listensphere.protocol.v1.AudioStreamOpened.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.AudioStreamOpened.newBuilder((io.listensphere.protocol.v1.AudioStreamOpened) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 20;
  }
  /**
   * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
   */
  private void clearAudioStreamOpened() {
    if (payloadCase_ == 20) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int CLOSE_AUDIO_STREAM_FIELD_NUMBER = 21;
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   */
  @java.lang.Override
  public boolean hasCloseAudioStream() {
    return payloadCase_ == 21;
  }
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.CloseAudioStream getCloseAudioStream() {
    if (payloadCase_ == 21) {
       return (io.listensphere.protocol.v1.CloseAudioStream) payload_;
    }
    return io.listensphere.protocol.v1.CloseAudioStream.getDefaultInstance();
  }
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   */
  private void setCloseAudioStream(io.listensphere.protocol.v1.CloseAudioStream value) {
    value.getClass();
  payload_ = value;
    payloadCase_ = 21;
  }
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   */
  private void mergeCloseAudioStream(io.listensphere.protocol.v1.CloseAudioStream value) {
    value.getClass();
  if (payloadCase_ == 21 &&
        payload_ != io.listensphere.protocol.v1.CloseAudioStream.getDefaultInstance()) {
      payload_ = io.listensphere.protocol.v1.CloseAudioStream.newBuilder((io.listensphere.protocol.v1.CloseAudioStream) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 21;
  }
  /**
   * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
   */
  private void clearCloseAudioStream() {
    if (payloadCase_ == 21) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static io.listensphere.protocol.v1.Envelope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.Envelope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.Envelope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.Envelope prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.Envelope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.Envelope, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.Envelope)
      io.listensphere.protocol.v1.EnvelopeOrBuilder {
    // Construct using io.listensphere.protocol.v1.Envelope.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public PayloadCase
        getPayloadCase() {
      return instance.getPayloadCase();
    }

    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }


    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.ProtocolVersion getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    public Builder setVersion(io.listensphere.protocol.v1.ProtocolVersion value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
      }
    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    public Builder setVersion(
        io.listensphere.protocol.v1.ProtocolVersion.Builder builderForValue) {
      copyOnWrite();
      instance.setVersion(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    public Builder mergeVersion(io.listensphere.protocol.v1.ProtocolVersion value) {
      copyOnWrite();
      instance.mergeVersion(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ProtocolVersion version = 1;</code>
     */
    public Builder clearVersion() {  copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>fixed64 request_id = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return instance.getRequestId();
    }
    /**
     * <code>fixed64 request_id = 2;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {
      copyOnWrite();
      instance.setRequestId(value);
      return this;
    }
    /**
     * <code>fixed64 request_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      copyOnWrite();
      instance.clearRequestId();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    @java.lang.Override
    public boolean hasPairRequest() {
      return instance.hasPairRequest();
    }
    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.PairRequest getPairRequest() {
      return instance.getPairRequest();
    }
    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    public Builder setPairRequest(io.listensphere.protocol.v1.PairRequest value) {
      copyOnWrite();
      instance.setPairRequest(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    public Builder setPairRequest(
        io.listensphere.protocol.v1.PairRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setPairRequest(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    public Builder mergePairRequest(io.listensphere.protocol.v1.PairRequest value) {
      copyOnWrite();
      instance.mergePairRequest(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairRequest pair_request = 10;</code>
     */
    public Builder clearPairRequest() {
      copyOnWrite();
      instance.clearPairRequest();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    @java.lang.Override
    public boolean hasPairResponse() {
      return instance.hasPairResponse();
    }
    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.PairResponse getPairResponse() {
      return instance.getPairResponse();
    }
    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    public Builder setPairResponse(io.listensphere.protocol.v1.PairResponse value) {
      copyOnWrite();
      instance.setPairResponse(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    public Builder setPairResponse(
        io.listensphere.protocol.v1.PairResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setPairResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    public Builder mergePairResponse(io.listensphere.protocol.v1.PairResponse value) {
      copyOnWrite();
      instance.mergePairResponse(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.PairResponse pair_response = 11;</code>
     */
    public Builder clearPairResponse() {
      copyOnWrite();
      instance.clearPairResponse();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return instance.hasHeartbeat();
    }
    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.Heartbeat getHeartbeat() {
      return instance.getHeartbeat();
    }
    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    public Builder setHeartbeat(io.listensphere.protocol.v1.Heartbeat value) {
      copyOnWrite();
      instance.setHeartbeat(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    public Builder setHeartbeat(
        io.listensphere.protocol.v1.Heartbeat.Builder builderForValue) {
      copyOnWrite();
      instance.setHeartbeat(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    public Builder mergeHeartbeat(io.listensphere.protocol.v1.Heartbeat value) {
      copyOnWrite();
      instance.mergeHeartbeat(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Heartbeat heartbeat = 12;</code>
     */
    public Builder clearHeartbeat() {
      copyOnWrite();
      instance.clearHeartbeat();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    @java.lang.Override
    public boolean hasStartStream() {
      return instance.hasStartStream();
    }
    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.StartStream getStartStream() {
      return instance.getStartStream();
    }
    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    public Builder setStartStream(io.listensphere.protocol.v1.StartStream value) {
      copyOnWrite();
      instance.setStartStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    public Builder setStartStream(
        io.listensphere.protocol.v1.StartStream.Builder builderForValue) {
      copyOnWrite();
      instance.setStartStream(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    public Builder mergeStartStream(io.listensphere.protocol.v1.StartStream value) {
      copyOnWrite();
      instance.mergeStartStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StartStream start_stream = 13;</code>
     */
    public Builder clearStartStream() {
      copyOnWrite();
      instance.clearStartStream();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    @java.lang.Override
    public boolean hasStopStream() {
      return instance.hasStopStream();
    }
    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.StopStream getStopStream() {
      return instance.getStopStream();
    }
    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    public Builder setStopStream(io.listensphere.protocol.v1.StopStream value) {
      copyOnWrite();
      instance.setStopStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    public Builder setStopStream(
        io.listensphere.protocol.v1.StopStream.Builder builderForValue) {
      copyOnWrite();
      instance.setStopStream(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    public Builder mergeStopStream(io.listensphere.protocol.v1.StopStream value) {
      copyOnWrite();
      instance.mergeStopStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.StopStream stop_stream = 14;</code>
     */
    public Builder clearStopStream() {
      copyOnWrite();
      instance.clearStopStream();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    @java.lang.Override
    public boolean hasHelloRequest() {
      return instance.hasHelloRequest();
    }
    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.HelloRequest getHelloRequest() {
      return instance.getHelloRequest();
    }
    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    public Builder setHelloRequest(io.listensphere.protocol.v1.HelloRequest value) {
      copyOnWrite();
      instance.setHelloRequest(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    public Builder setHelloRequest(
        io.listensphere.protocol.v1.HelloRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setHelloRequest(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    public Builder mergeHelloRequest(io.listensphere.protocol.v1.HelloRequest value) {
      copyOnWrite();
      instance.mergeHelloRequest(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloRequest hello_request = 15;</code>
     */
    public Builder clearHelloRequest() {
      copyOnWrite();
      instance.clearHelloRequest();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    @java.lang.Override
    public boolean hasHelloResponse() {
      return instance.hasHelloResponse();
    }
    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.HelloResponse getHelloResponse() {
      return instance.getHelloResponse();
    }
    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    public Builder setHelloResponse(io.listensphere.protocol.v1.HelloResponse value) {
      copyOnWrite();
      instance.setHelloResponse(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    public Builder setHelloResponse(
        io.listensphere.protocol.v1.HelloResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setHelloResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    public Builder mergeHelloResponse(io.listensphere.protocol.v1.HelloResponse value) {
      copyOnWrite();
      instance.mergeHelloResponse(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HelloResponse hello_response = 16;</code>
     */
    public Builder clearHelloResponse() {
      copyOnWrite();
      instance.clearHelloResponse();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    @java.lang.Override
    public boolean hasHeartbeatAck() {
      return instance.hasHeartbeatAck();
    }
    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.HeartbeatAck getHeartbeatAck() {
      return instance.getHeartbeatAck();
    }
    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    public Builder setHeartbeatAck(io.listensphere.protocol.v1.HeartbeatAck value) {
      copyOnWrite();
      instance.setHeartbeatAck(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    public Builder setHeartbeatAck(
        io.listensphere.protocol.v1.HeartbeatAck.Builder builderForValue) {
      copyOnWrite();
      instance.setHeartbeatAck(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    public Builder mergeHeartbeatAck(io.listensphere.protocol.v1.HeartbeatAck value) {
      copyOnWrite();
      instance.mergeHeartbeatAck(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.HeartbeatAck heartbeat_ack = 17;</code>
     */
    public Builder clearHeartbeatAck() {
      copyOnWrite();
      instance.clearHeartbeatAck();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    @java.lang.Override
    public boolean hasDisconnect() {
      return instance.hasDisconnect();
    }
    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.Disconnect getDisconnect() {
      return instance.getDisconnect();
    }
    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    public Builder setDisconnect(io.listensphere.protocol.v1.Disconnect value) {
      copyOnWrite();
      instance.setDisconnect(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    public Builder setDisconnect(
        io.listensphere.protocol.v1.Disconnect.Builder builderForValue) {
      copyOnWrite();
      instance.setDisconnect(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    public Builder mergeDisconnect(io.listensphere.protocol.v1.Disconnect value) {
      copyOnWrite();
      instance.mergeDisconnect(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.Disconnect disconnect = 18;</code>
     */
    public Builder clearDisconnect() {
      copyOnWrite();
      instance.clearDisconnect();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    @java.lang.Override
    public boolean hasOpenAudioStream() {
      return instance.hasOpenAudioStream();
    }
    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.OpenAudioStream getOpenAudioStream() {
      return instance.getOpenAudioStream();
    }
    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    public Builder setOpenAudioStream(io.listensphere.protocol.v1.OpenAudioStream value) {
      copyOnWrite();
      instance.setOpenAudioStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    public Builder setOpenAudioStream(
        io.listensphere.protocol.v1.OpenAudioStream.Builder builderForValue) {
      copyOnWrite();
      instance.setOpenAudioStream(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    public Builder mergeOpenAudioStream(io.listensphere.protocol.v1.OpenAudioStream value) {
      copyOnWrite();
      instance.mergeOpenAudioStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.OpenAudioStream open_audio_stream = 19;</code>
     */
    public Builder clearOpenAudioStream() {
      copyOnWrite();
      instance.clearOpenAudioStream();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    @java.lang.Override
    public boolean hasAudioStreamOpened() {
      return instance.hasAudioStreamOpened();
    }
    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.AudioStreamOpened getAudioStreamOpened() {
      return instance.getAudioStreamOpened();
    }
    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    public Builder setAudioStreamOpened(io.listensphere.protocol.v1.AudioStreamOpened value) {
      copyOnWrite();
      instance.setAudioStreamOpened(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    public Builder setAudioStreamOpened(
        io.listensphere.protocol.v1.AudioStreamOpened.Builder builderForValue) {
      copyOnWrite();
      instance.setAudioStreamOpened(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    public Builder mergeAudioStreamOpened(io.listensphere.protocol.v1.AudioStreamOpened value) {
      copyOnWrite();
      instance.mergeAudioStreamOpened(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.AudioStreamOpened audio_stream_opened = 20;</code>
     */
    public Builder clearAudioStreamOpened() {
      copyOnWrite();
      instance.clearAudioStreamOpened();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    @java.lang.Override
    public boolean hasCloseAudioStream() {
      return instance.hasCloseAudioStream();
    }
    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.CloseAudioStream getCloseAudioStream() {
      return instance.getCloseAudioStream();
    }
    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    public Builder setCloseAudioStream(io.listensphere.protocol.v1.CloseAudioStream value) {
      copyOnWrite();
      instance.setCloseAudioStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    public Builder setCloseAudioStream(
        io.listensphere.protocol.v1.CloseAudioStream.Builder builderForValue) {
      copyOnWrite();
      instance.setCloseAudioStream(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    public Builder mergeCloseAudioStream(io.listensphere.protocol.v1.CloseAudioStream value) {
      copyOnWrite();
      instance.mergeCloseAudioStream(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.CloseAudioStream close_audio_stream = 21;</code>
     */
    public Builder clearCloseAudioStream() {
      copyOnWrite();
      instance.clearCloseAudioStream();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.Envelope)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.Envelope();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "payload_",
            "payloadCase_",
            "bitField0_",
            "version_",
            "requestId_",
            io.listensphere.protocol.v1.PairRequest.class,
            io.listensphere.protocol.v1.PairResponse.class,
            io.listensphere.protocol.v1.Heartbeat.class,
            io.listensphere.protocol.v1.StartStream.class,
            io.listensphere.protocol.v1.StopStream.class,
            io.listensphere.protocol.v1.HelloRequest.class,
            io.listensphere.protocol.v1.HelloResponse.class,
            io.listensphere.protocol.v1.HeartbeatAck.class,
            io.listensphere.protocol.v1.Disconnect.class,
            io.listensphere.protocol.v1.OpenAudioStream.class,
            io.listensphere.protocol.v1.AudioStreamOpened.class,
            io.listensphere.protocol.v1.CloseAudioStream.class,
          };
          java.lang.String info =
              "\u0000\u000e\u0001\u0001\u0001\u0015\u000e\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u0005\n<\u0000\u000b<\u0000\f<\u0000\r<\u0000\u000e<\u0000\u000f<\u0000\u0010<\u0000" +
              "\u0011<\u0000\u0012<\u0000\u0013<\u0000\u0014<\u0000\u0015<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.Envelope> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.Envelope.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.Envelope>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.Envelope)
  private static final io.listensphere.protocol.v1.Envelope DEFAULT_INSTANCE;
  static {
    Envelope defaultInstance = new Envelope();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Envelope.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.Envelope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Envelope> PARSER;

  public static com.google.protobuf.Parser<Envelope> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

