// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf enum {@code listensphere.protocol.v1.ErrorCode}
 */
public enum ErrorCode
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  ERROR_CODE_UNSPECIFIED(0),
  /**
   * <code>ERROR_CODE_INCOMPATIBLE_VERSION = 1;</code>
   */
  ERROR_CODE_INCOMPATIBLE_VERSION(1),
  /**
   * <code>ERROR_CODE_NOT_PAIRED = 2;</code>
   */
  ERROR_CODE_NOT_PAIRED(2),
  /**
   * <code>ERROR_CODE_PAIRING_CODE_INVALID = 3;</code>
   */
  ERROR_CODE_PAIRING_CODE_INVALID(3),
  /**
   * <code>ERROR_CODE_PAIRING_RATE_LIMITED = 4;</code>
   */
  ERROR_CODE_PAIRING_RATE_LIMITED(4),
  /**
   * <code>ERROR_CODE_CAPABILITY_NOT_SUPPORTED = 5;</code>
   */
  ERROR_CODE_CAPABILITY_NOT_SUPPORTED(5),
  /**
   * <code>ERROR_CODE_STREAM_REJECTED = 6;</code>
   */
  ERROR_CODE_STREAM_REJECTED(6),
  /**
   * <code>ERROR_CODE_INTERNAL = 7;</code>
   */
  ERROR_CODE_INTERNAL(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  public static final int ERROR_CODE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ERROR_CODE_INCOMPATIBLE_VERSION = 1;</code>
   */
  public static final int ERROR_CODE_INCOMPATIBLE_VERSION_VALUE = 1;
  /**
   * <code>ERROR_CODE_NOT_PAIRED = 2;</code>
   */
  public static final int ERROR_CODE_NOT_PAIRED_VALUE = 2;
  /**
   * <code>ERROR_CODE_PAIRING_CODE_INVALID = 3;</code>
   */
  public static final int ERROR_CODE_PAIRING_CODE_INVALID_VALUE = 3;
  /**
   * <code>ERROR_CODE_PAIRING_RATE_LIMITED = 4;</code>
   */
  public static final int ERROR_CODE_PAIRING_RATE_LIMITED_VALUE = 4;
  /**
   * <code>ERROR_CODE_CAPABILITY_NOT_SUPPORTED = 5;</code>
   */
  public static final int ERROR_CODE_CAPABILITY_NOT_SUPPORTED_VALUE = 5;
  /**
   * <code>ERROR_CODE_STREAM_REJECTED = 6;</code>
   */
  public static final int ERROR_CODE_STREAM_REJECTED_VALUE = 6;
  /**
   * <code>ERROR_CODE_INTERNAL = 7;</code>
   */
  public static final int ERROR_CODE_INTERNAL_VALUE = 7;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCode valueOf(int value) {
    return forNumber(value);
  }

  public static ErrorCode forNumber(int value) {
    switch (value) {
      case 0: return ERROR_CODE_UNSPECIFIED;
      case 1: return ERROR_CODE_INCOMPATIBLE_VERSION;
      case 2: return ERROR_CODE_NOT_PAIRED;
      case 3: return ERROR_CODE_PAIRING_CODE_INVALID;
      case 4: return ERROR_CODE_PAIRING_RATE_LIMITED;
      case 5: return ERROR_CODE_CAPABILITY_NOT_SUPPORTED;
      case 6: return ERROR_CODE_STREAM_REJECTED;
      case 7: return ERROR_CODE_INTERNAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
          @java.lang.Override
          public ErrorCode findValueByNumber(int number) {
            return ErrorCode.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ErrorCodeVerifier.INSTANCE;
  }

  private static final class ErrorCodeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ErrorCodeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ErrorCode.forNumber(number) != null;
          }
        };

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:listensphere.protocol.v1.ErrorCode)
}

