// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface HeartbeatAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.HeartbeatAck)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 echo_monotonic_milliseconds = 1;</code>
   * @return The echoMonotonicMilliseconds.
   */
  long getEchoMonotonicMilliseconds();

  /**
   * <code>uint64 responder_monotonic_milliseconds = 2;</code>
   * @return The responderMonotonicMilliseconds.
   */
  long getResponderMonotonicMilliseconds();
}
