// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.Heartbeat}
 */
public  final class Heartbeat extends
    com.google.protobuf.GeneratedMessageLite<
        Heartbeat, Heartbeat.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.Heartbeat)
    HeartbeatOrBuilder {
  private Heartbeat() {
  }
  public static final int MONOTONIC_MILLISECONDS_FIELD_NUMBER = 1;
  private long monotonicMilliseconds_;
  /**
   * <code>uint64 monotonic_milliseconds = 1;</code>
   * @return The monotonicMilliseconds.
   */
  @java.lang.Override
  public long getMonotonicMilliseconds() {
    return monotonicMilliseconds_;
  }
  /**
   * <code>uint64 monotonic_milliseconds = 1;</code>
   * @param value The monotonicMilliseconds to set.
   */
  private void setMonotonicMilliseconds(long value) {
    
    monotonicMilliseconds_ = value;
  }
  /**
   * <code>uint64 monotonic_milliseconds = 1;</code>
   */
  private void clearMonotonicMilliseconds() {

    monotonicMilliseconds_ = 0L;
  }

  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.Heartbeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.Heartbeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.Heartbeat prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.Heartbeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.Heartbeat, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.Heartbeat)
      io.listensphere.protocol.v1.HeartbeatOrBuilder {
    // Construct using io.listensphere.protocol.v1.Heartbeat.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 monotonic_milliseconds = 1;</code>
     * @return The monotonicMilliseconds.
     */
    @java.lang.Override
    public long getMonotonicMilliseconds() {
      return instance.getMonotonicMilliseconds();
    }
    /**
     * <code>uint64 monotonic_milliseconds = 1;</code>
     * @param value The monotonicMilliseconds to set.
     * @return This builder for chaining.
     */
    public Builder setMonotonicMilliseconds(long value) {
      copyOnWrite();
      instance.setMonotonicMilliseconds(value);
      return this;
    }
    /**
     * <code>uint64 monotonic_milliseconds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonotonicMilliseconds() {
      copyOnWrite();
      instance.clearMonotonicMilliseconds();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.Heartbeat)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.Heartbeat();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "monotonicMilliseconds_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.Heartbeat> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.Heartbeat.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.Heartbeat>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.Heartbeat)
  private static final io.listensphere.protocol.v1.Heartbeat DEFAULT_INSTANCE;
  static {
    Heartbeat defaultInstance = new Heartbeat();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Heartbeat.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.Heartbeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Heartbeat> PARSER;

  public static com.google.protobuf.Parser<Heartbeat> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

