// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.HeartbeatAck}
 */
public  final class HeartbeatAck extends
    com.google.protobuf.GeneratedMessageLite<
        HeartbeatAck, HeartbeatAck.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.HeartbeatAck)
    HeartbeatAckOrBuilder {
  private HeartbeatAck() {
  }
  public static final int ECHO_MONOTONIC_MILLISECONDS_FIELD_NUMBER = 1;
  private long echoMonotonicMilliseconds_;
  /**
   * <code>uint64 echo_monotonic_milliseconds = 1;</code>
   * @return The echoMonotonicMilliseconds.
   */
  @java.lang.Override
  public long getEchoMonotonicMilliseconds() {
    return echoMonotonicMilliseconds_;
  }
  /**
   * <code>uint64 echo_monotonic_milliseconds = 1;</code>
   * @param value The echoMonotonicMilliseconds to set.
   */
  private void setEchoMonotonicMilliseconds(long value) {
    
    echoMonotonicMilliseconds_ = value;
  }
  /**
   * <code>uint64 echo_monotonic_milliseconds = 1;</code>
   */
  private void clearEchoMonotonicMilliseconds() {

    echoMonotonicMilliseconds_ = 0L;
  }

  public static final int RESPONDER_MONOTONIC_MILLISECONDS_FIELD_NUMBER = 2;
  private long responderMonotonicMilliseconds_;
  /**
   * <code>uint64 responder_monotonic_milliseconds = 2;</code>
   * @return The responderMonotonicMilliseconds.
   */
  @java.lang.Override
  public long getResponderMonotonicMilliseconds() {
    return responderMonotonicMilliseconds_;
  }
  /**
   * <code>uint64 responder_monotonic_milliseconds = 2;</code>
   * @param value The responderMonotonicMilliseconds to set.
   */
  private void setResponderMonotonicMilliseconds(long value) {
    
    responderMonotonicMilliseconds_ = value;
  }
  /**
   * <code>uint64 responder_monotonic_milliseconds = 2;</code>
   */
  private void clearResponderMonotonicMilliseconds() {

    responderMonotonicMilliseconds_ = 0L;
  }

  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.HeartbeatAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.HeartbeatAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HeartbeatAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.HeartbeatAck prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.HeartbeatAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.HeartbeatAck, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.HeartbeatAck)
      io.listensphere.protocol.v1.HeartbeatAckOrBuilder {
    // Construct using io.listensphere.protocol.v1.HeartbeatAck.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 echo_monotonic_milliseconds = 1;</code>
     * @return The echoMonotonicMilliseconds.
     */
    @java.lang.Override
    public long getEchoMonotonicMilliseconds() {
      return instance.getEchoMonotonicMilliseconds();
    }
    /**
     * <code>uint64 echo_monotonic_milliseconds = 1;</code>
     * @param value The echoMonotonicMilliseconds to set.
     * @return This builder for chaining.
     */
    public Builder setEchoMonotonicMilliseconds(long value) {
      copyOnWrite();
      instance.setEchoMonotonicMilliseconds(value);
      return this;
    }
    /**
     * <code>uint64 echo_monotonic_milliseconds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEchoMonotonicMilliseconds() {
      copyOnWrite();
      instance.clearEchoMonotonicMilliseconds();
      return this;
    }

    /**
     * <code>uint64 responder_monotonic_milliseconds = 2;</code>
     * @return The responderMonotonicMilliseconds.
     */
    @java.lang.Override
    public long getResponderMonotonicMilliseconds() {
      return instance.getResponderMonotonicMilliseconds();
    }
    /**
     * <code>uint64 responder_monotonic_milliseconds = 2;</code>
     * @param value The responderMonotonicMilliseconds to set.
     * @return This builder for chaining.
     */
    public Builder setResponderMonotonicMilliseconds(long value) {
      copyOnWrite();
      instance.setResponderMonotonicMilliseconds(value);
      return this;
    }
    /**
     * <code>uint64 responder_monotonic_milliseconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponderMonotonicMilliseconds() {
      copyOnWrite();
      instance.clearResponderMonotonicMilliseconds();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.HeartbeatAck)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.HeartbeatAck();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "echoMonotonicMilliseconds_",
            "responderMonotonicMilliseconds_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0003\u0002\u0003" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.HeartbeatAck> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.HeartbeatAck.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.HeartbeatAck>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.HeartbeatAck)
  private static final io.listensphere.protocol.v1.HeartbeatAck DEFAULT_INSTANCE;
  static {
    HeartbeatAck defaultInstance = new HeartbeatAck();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HeartbeatAck.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.HeartbeatAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HeartbeatAck> PARSER;

  public static com.google.protobuf.Parser<HeartbeatAck> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

