// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.Heartbeat)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 monotonic_milliseconds = 1;</code>
   * @return The monotonicMilliseconds.
   */
  long getMonotonicMilliseconds();
}
