// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.HelloResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   * @return Whether the controller field is set.
   */
  boolean hasController();
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   * @return The controller.
   */
  io.listensphere.protocol.v1.DeviceIdentity getController();

  /**
   * <code>bool paired = 2;</code>
   * @return The paired.
   */
  boolean getPaired();

  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The error.
   */
  io.listensphere.protocol.v1.ErrorCode getError();
}
