// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.HelloRequest}
 */
public  final class HelloRequest extends
    com.google.protobuf.GeneratedMessageLite<
        HelloRequest, HelloRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.HelloRequest)
    HelloRequestOrBuilder {
  private HelloRequest() {
    deviceCertificate_ = com.google.protobuf.ByteString.EMPTY;
    clientNonce_ = com.google.protobuf.ByteString.EMPTY;
    identitySignature_ = com.google.protobuf.ByteString.EMPTY;
    sourceId_ = "";
    sourceName_ = "";
    sourceKind_ = "";
  }
  private int bitField0_;
  public static final int DEVICE_FIELD_NUMBER = 1;
  private io.listensphere.protocol.v1.DeviceIdentity device_;
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   */
  @java.lang.Override
  public boolean hasDevice() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.DeviceIdentity getDevice() {
    return device_ == null ? io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance() : device_;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   */
  private void setDevice(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  device_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDevice(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  if (device_ != null &&
        device_ != io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance()) {
      device_ =
        io.listensphere.protocol.v1.DeviceIdentity.newBuilder(device_).mergeFrom(value).buildPartial();
    } else {
      device_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   */
  private void clearDevice() {  device_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int DEVICE_CERTIFICATE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString deviceCertificate_;
  /**
   * <code>bytes device_certificate = 2;</code>
   * @return The deviceCertificate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDeviceCertificate() {
    return deviceCertificate_;
  }
  /**
   * <code>bytes device_certificate = 2;</code>
   * @param value The deviceCertificate to set.
   */
  private void setDeviceCertificate(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceCertificate_ = value;
  }
  /**
   * <code>bytes device_certificate = 2;</code>
   */
  private void clearDeviceCertificate() {

    deviceCertificate_ = getDefaultInstance().getDeviceCertificate();
  }

  public static final int CLIENT_NONCE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString clientNonce_;
  /**
   * <code>bytes client_nonce = 3;</code>
   * @return The clientNonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getClientNonce() {
    return clientNonce_;
  }
  /**
   * <code>bytes client_nonce = 3;</code>
   * @param value The clientNonce to set.
   */
  private void setClientNonce(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientNonce_ = value;
  }
  /**
   * <code>bytes client_nonce = 3;</code>
   */
  private void clearClientNonce() {

    clientNonce_ = getDefaultInstance().getClientNonce();
  }

  public static final int IDENTITY_SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString identitySignature_;
  /**
   * <code>bytes identity_signature = 4;</code>
   * @return The identitySignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIdentitySignature() {
    return identitySignature_;
  }
  /**
   * <code>bytes identity_signature = 4;</code>
   * @param value The identitySignature to set.
   */
  private void setIdentitySignature(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    identitySignature_ = value;
  }
  /**
   * <code>bytes identity_signature = 4;</code>
   */
  private void clearIdentitySignature() {

    identitySignature_ = getDefaultInstance().getIdentitySignature();
  }

  public static final int SOURCE_ID_FIELD_NUMBER = 5;
  private java.lang.String sourceId_;
  /**
   * <code>string source_id = 5;</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public java.lang.String getSourceId() {
    return sourceId_;
  }
  /**
   * <code>string source_id = 5;</code>
   * @return The bytes for sourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceId_);
  }
  /**
   * <code>string source_id = 5;</code>
   * @param value The sourceId to set.
   */
  private void setSourceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sourceId_ = value;
  }
  /**
   * <code>string source_id = 5;</code>
   */
  private void clearSourceId() {

    sourceId_ = getDefaultInstance().getSourceId();
  }
  /**
   * <code>string source_id = 5;</code>
   * @param value The bytes for sourceId to set.
   */
  private void setSourceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceId_ = value.toStringUtf8();

  }

  public static final int SOURCE_NAME_FIELD_NUMBER = 6;
  private java.lang.String sourceName_;
  /**
   * <code>string source_name = 6;</code>
   * @return The sourceName.
   */
  @java.lang.Override
  public java.lang.String getSourceName() {
    return sourceName_;
  }
  /**
   * <code>string source_name = 6;</code>
   * @return The bytes for sourceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceName_);
  }
  /**
   * <code>string source_name = 6;</code>
   * @param value The sourceName to set.
   */
  private void setSourceName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sourceName_ = value;
  }
  /**
   * <code>string source_name = 6;</code>
   */
  private void clearSourceName() {

    sourceName_ = getDefaultInstance().getSourceName();
  }
  /**
   * <code>string source_name = 6;</code>
   * @param value The bytes for sourceName to set.
   */
  private void setSourceNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceName_ = value.toStringUtf8();

  }

  public static final int SOURCE_KIND_FIELD_NUMBER = 7;
  private java.lang.String sourceKind_;
  /**
   * <code>string source_kind = 7;</code>
   * @return The sourceKind.
   */
  @java.lang.Override
  public java.lang.String getSourceKind() {
    return sourceKind_;
  }
  /**
   * <code>string source_kind = 7;</code>
   * @return The bytes for sourceKind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceKindBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceKind_);
  }
  /**
   * <code>string source_kind = 7;</code>
   * @param value The sourceKind to set.
   */
  private void setSourceKind(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sourceKind_ = value;
  }
  /**
   * <code>string source_kind = 7;</code>
   */
  private void clearSourceKind() {

    sourceKind_ = getDefaultInstance().getSourceKind();
  }
  /**
   * <code>string source_kind = 7;</code>
   * @param value The bytes for sourceKind to set.
   */
  private void setSourceKindBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceKind_ = value.toStringUtf8();

  }

  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.HelloRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.HelloRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.HelloRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.HelloRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.HelloRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.HelloRequest)
      io.listensphere.protocol.v1.HelloRequestOrBuilder {
    // Construct using io.listensphere.protocol.v1.HelloRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    @java.lang.Override
    public boolean hasDevice() {
      return instance.hasDevice();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.DeviceIdentity getDevice() {
      return instance.getDevice();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    public Builder setDevice(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.setDevice(value);
      return this;
      }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    public Builder setDevice(
        io.listensphere.protocol.v1.DeviceIdentity.Builder builderForValue) {
      copyOnWrite();
      instance.setDevice(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    public Builder mergeDevice(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.mergeDevice(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
     */
    public Builder clearDevice() {  copyOnWrite();
      instance.clearDevice();
      return this;
    }

    /**
     * <code>bytes device_certificate = 2;</code>
     * @return The deviceCertificate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDeviceCertificate() {
      return instance.getDeviceCertificate();
    }
    /**
     * <code>bytes device_certificate = 2;</code>
     * @param value The deviceCertificate to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceCertificate(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceCertificate(value);
      return this;
    }
    /**
     * <code>bytes device_certificate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceCertificate() {
      copyOnWrite();
      instance.clearDeviceCertificate();
      return this;
    }

    /**
     * <code>bytes client_nonce = 3;</code>
     * @return The clientNonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientNonce() {
      return instance.getClientNonce();
    }
    /**
     * <code>bytes client_nonce = 3;</code>
     * @param value The clientNonce to set.
     * @return This builder for chaining.
     */
    public Builder setClientNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientNonce(value);
      return this;
    }
    /**
     * <code>bytes client_nonce = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientNonce() {
      copyOnWrite();
      instance.clearClientNonce();
      return this;
    }

    /**
     * <code>bytes identity_signature = 4;</code>
     * @return The identitySignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentitySignature() {
      return instance.getIdentitySignature();
    }
    /**
     * <code>bytes identity_signature = 4;</code>
     * @param value The identitySignature to set.
     * @return This builder for chaining.
     */
    public Builder setIdentitySignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdentitySignature(value);
      return this;
    }
    /**
     * <code>bytes identity_signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentitySignature() {
      copyOnWrite();
      instance.clearIdentitySignature();
      return this;
    }

    /**
     * <code>string source_id = 5;</code>
     * @return The sourceId.
     */
    @java.lang.Override
    public java.lang.String getSourceId() {
      return instance.getSourceId();
    }
    /**
     * <code>string source_id = 5;</code>
     * @return The bytes for sourceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      return instance.getSourceIdBytes();
    }
    /**
     * <code>string source_id = 5;</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceId(value);
      return this;
    }
    /**
     * <code>string source_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      copyOnWrite();
      instance.clearSourceId();
      return this;
    }
    /**
     * <code>string source_id = 5;</code>
     * @param value The bytes for sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceIdBytes(value);
      return this;
    }

    /**
     * <code>string source_name = 6;</code>
     * @return The sourceName.
     */
    @java.lang.Override
    public java.lang.String getSourceName() {
      return instance.getSourceName();
    }
    /**
     * <code>string source_name = 6;</code>
     * @return The bytes for sourceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      return instance.getSourceNameBytes();
    }
    /**
     * <code>string source_name = 6;</code>
     * @param value The sourceName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceName(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceName(value);
      return this;
    }
    /**
     * <code>string source_name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceName() {
      copyOnWrite();
      instance.clearSourceName();
      return this;
    }
    /**
     * <code>string source_name = 6;</code>
     * @param value The bytes for sourceName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceNameBytes(value);
      return this;
    }

    /**
     * <code>string source_kind = 7;</code>
     * @return The sourceKind.
     */
    @java.lang.Override
    public java.lang.String getSourceKind() {
      return instance.getSourceKind();
    }
    /**
     * <code>string source_kind = 7;</code>
     * @return The bytes for sourceKind.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceKindBytes() {
      return instance.getSourceKindBytes();
    }
    /**
     * <code>string source_kind = 7;</code>
     * @param value The sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKind(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceKind(value);
      return this;
    }
    /**
     * <code>string source_kind = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceKind() {
      copyOnWrite();
      instance.clearSourceKind();
      return this;
    }
    /**
     * <code>string source_kind = 7;</code>
     * @param value The bytes for sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKindBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceKindBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.HelloRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.HelloRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "device_",
            "deviceCertificate_",
            "clientNonce_",
            "identitySignature_",
            "sourceId_",
            "sourceName_",
            "sourceKind_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\n\u0003\n\u0004\n\u0005\u0208\u0006\u0208\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.HelloRequest> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.HelloRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.HelloRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.HelloRequest)
  private static final io.listensphere.protocol.v1.HelloRequest DEFAULT_INSTANCE;
  static {
    HelloRequest defaultInstance = new HelloRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HelloRequest.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.HelloRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HelloRequest> PARSER;

  public static com.google.protobuf.Parser<HelloRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

