// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.HelloRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   * @return Whether the device field is set.
   */
  boolean hasDevice();
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity device = 1;</code>
   * @return The device.
   */
  io.listensphere.protocol.v1.DeviceIdentity getDevice();

  /**
   * <code>bytes device_certificate = 2;</code>
   * @return The deviceCertificate.
   */
  com.google.protobuf.ByteString getDeviceCertificate();

  /**
   * <code>bytes client_nonce = 3;</code>
   * @return The clientNonce.
   */
  com.google.protobuf.ByteString getClientNonce();

  /**
   * <code>bytes identity_signature = 4;</code>
   * @return The identitySignature.
   */
  com.google.protobuf.ByteString getIdentitySignature();

  /**
   * <code>string source_id = 5;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string source_id = 5;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string source_name = 6;</code>
   * @return The sourceName.
   */
  java.lang.String getSourceName();
  /**
   * <code>string source_name = 6;</code>
   * @return The bytes for sourceName.
   */
  com.google.protobuf.ByteString
      getSourceNameBytes();

  /**
   * <code>string source_kind = 7;</code>
   * @return The sourceKind.
   */
  java.lang.String getSourceKind();
  /**
   * <code>string source_kind = 7;</code>
   * @return The bytes for sourceKind.
   */
  com.google.protobuf.ByteString
      getSourceKindBytes();
}
