// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.HelloResponse}
 */
public  final class HelloResponse extends
    com.google.protobuf.GeneratedMessageLite<
        HelloResponse, HelloResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.HelloResponse)
    HelloResponseOrBuilder {
  private HelloResponse() {
  }
  private int bitField0_;
  public static final int CONTROLLER_FIELD_NUMBER = 1;
  private io.listensphere.protocol.v1.DeviceIdentity controller_;
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   */
  @java.lang.Override
  public boolean hasController() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.DeviceIdentity getController() {
    return controller_ == null ? io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance() : controller_;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   */
  private void setController(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  controller_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeController(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  if (controller_ != null &&
        controller_ != io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance()) {
      controller_ =
        io.listensphere.protocol.v1.DeviceIdentity.newBuilder(controller_).mergeFrom(value).buildPartial();
    } else {
      controller_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
   */
  private void clearController() {  controller_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int PAIRED_FIELD_NUMBER = 2;
  private boolean paired_;
  /**
   * <code>bool paired = 2;</code>
   * @return The paired.
   */
  @java.lang.Override
  public boolean getPaired() {
    return paired_;
  }
  /**
   * <code>bool paired = 2;</code>
   * @param value The paired to set.
   */
  private void setPaired(boolean value) {
    
    paired_ = value;
  }
  /**
   * <code>bool paired = 2;</code>
   */
  private void clearPaired() {

    paired_ = false;
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private int error_;
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The enum numeric value on the wire for error.
   */
  @java.lang.Override
  public int getErrorValue() {
    return error_;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.ErrorCode getError() {
    io.listensphere.protocol.v1.ErrorCode result = io.listensphere.protocol.v1.ErrorCode.forNumber(error_);
    return result == null ? io.listensphere.protocol.v1.ErrorCode.UNRECOGNIZED : result;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @param value The enum numeric value on the wire for error to set.
   */
  private void setErrorValue(int value) {
      error_ = value;
  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @param value The error to set.
   */
  private void setError(io.listensphere.protocol.v1.ErrorCode value) {
    error_ = value.getNumber();

  }
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   */
  private void clearError() {

    error_ = 0;
  }

  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.HelloResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.HelloResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.HelloResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.HelloResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.HelloResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.HelloResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.HelloResponse)
      io.listensphere.protocol.v1.HelloResponseOrBuilder {
    // Construct using io.listensphere.protocol.v1.HelloResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    @java.lang.Override
    public boolean hasController() {
      return instance.hasController();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.DeviceIdentity getController() {
      return instance.getController();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    public Builder setController(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.setController(value);
      return this;
      }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    public Builder setController(
        io.listensphere.protocol.v1.DeviceIdentity.Builder builderForValue) {
      copyOnWrite();
      instance.setController(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    public Builder mergeController(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.mergeController(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity controller = 1;</code>
     */
    public Builder clearController() {  copyOnWrite();
      instance.clearController();
      return this;
    }

    /**
     * <code>bool paired = 2;</code>
     * @return The paired.
     */
    @java.lang.Override
    public boolean getPaired() {
      return instance.getPaired();
    }
    /**
     * <code>bool paired = 2;</code>
     * @param value The paired to set.
     * @return This builder for chaining.
     */
    public Builder setPaired(boolean value) {
      copyOnWrite();
      instance.setPaired(value);
      return this;
    }
    /**
     * <code>bool paired = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaired() {
      copyOnWrite();
      instance.clearPaired();
      return this;
    }

    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
     * @return The enum numeric value on the wire for error.
     */
    @java.lang.Override
    public int getErrorValue() {
      return instance.getErrorValue();
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorValue(int value) {
      copyOnWrite();
      instance.setErrorValue(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
     * @return The error.
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.ErrorCode getError() {
      return instance.getError();
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
     * @param value The enum numeric value on the wire for error to set.
     * @return This builder for chaining.
     */
    public Builder setError(io.listensphere.protocol.v1.ErrorCode value) {
      copyOnWrite();
      instance.setError(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      copyOnWrite();
      instance.clearError();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.HelloResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.HelloResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "controller_",
            "paired_",
            "error_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u0007\u0003\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.HelloResponse> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.HelloResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.HelloResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.HelloResponse)
  private static final io.listensphere.protocol.v1.HelloResponse DEFAULT_INSTANCE;
  static {
    HelloResponse defaultInstance = new HelloResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HelloResponse.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.HelloResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HelloResponse> PARSER;

  public static com.google.protobuf.Parser<HelloResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

