// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface OpenAudioStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.OpenAudioStream)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string source_id = 1;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string source_id = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string source_kind = 3;</code>
   * @return The sourceKind.
   */
  java.lang.String getSourceKind();
  /**
   * <code>string source_kind = 3;</code>
   * @return The bytes for sourceKind.
   */
  com.google.protobuf.ByteString
      getSourceKindBytes();
}
