// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.OpenAudioStream}
 */
public  final class OpenAudioStream extends
    com.google.protobuf.GeneratedMessageLite<
        OpenAudioStream, OpenAudioStream.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.OpenAudioStream)
    OpenAudioStreamOrBuilder {
  private OpenAudioStream() {
    sourceId_ = "";
    displayName_ = "";
    sourceKind_ = "";
  }
  public static final int SOURCE_ID_FIELD_NUMBER = 1;
  private java.lang.String sourceId_;
  /**
   * <code>string source_id = 1;</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public java.lang.String getSourceId() {
    return sourceId_;
  }
  /**
   * <code>string source_id = 1;</code>
   * @return The bytes for sourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceId_);
  }
  /**
   * <code>string source_id = 1;</code>
   * @param value The sourceId to set.
   */
  private void setSourceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sourceId_ = value;
  }
  /**
   * <code>string source_id = 1;</code>
   */
  private void clearSourceId() {

    sourceId_ = getDefaultInstance().getSourceId();
  }
  /**
   * <code>string source_id = 1;</code>
   * @param value The bytes for sourceId to set.
   */
  private void setSourceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceId_ = value.toStringUtf8();

  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 2;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    displayName_ = value;
  }
  /**
   * <code>string display_name = 2;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int SOURCE_KIND_FIELD_NUMBER = 3;
  private java.lang.String sourceKind_;
  /**
   * <code>string source_kind = 3;</code>
   * @return The sourceKind.
   */
  @java.lang.Override
  public java.lang.String getSourceKind() {
    return sourceKind_;
  }
  /**
   * <code>string source_kind = 3;</code>
   * @return The bytes for sourceKind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceKindBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceKind_);
  }
  /**
   * <code>string source_kind = 3;</code>
   * @param value The sourceKind to set.
   */
  private void setSourceKind(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sourceKind_ = value;
  }
  /**
   * <code>string source_kind = 3;</code>
   */
  private void clearSourceKind() {

    sourceKind_ = getDefaultInstance().getSourceKind();
  }
  /**
   * <code>string source_kind = 3;</code>
   * @param value The bytes for sourceKind to set.
   */
  private void setSourceKindBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceKind_ = value.toStringUtf8();

  }

  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.OpenAudioStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.OpenAudioStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.OpenAudioStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.OpenAudioStream prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.OpenAudioStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.OpenAudioStream, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.OpenAudioStream)
      io.listensphere.protocol.v1.OpenAudioStreamOrBuilder {
    // Construct using io.listensphere.protocol.v1.OpenAudioStream.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string source_id = 1;</code>
     * @return The sourceId.
     */
    @java.lang.Override
    public java.lang.String getSourceId() {
      return instance.getSourceId();
    }
    /**
     * <code>string source_id = 1;</code>
     * @return The bytes for sourceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      return instance.getSourceIdBytes();
    }
    /**
     * <code>string source_id = 1;</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceId(value);
      return this;
    }
    /**
     * <code>string source_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      copyOnWrite();
      instance.clearSourceId();
      return this;
    }
    /**
     * <code>string source_id = 1;</code>
     * @param value The bytes for sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceIdBytes(value);
      return this;
    }

    /**
     * <code>string display_name = 2;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 2;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>string source_kind = 3;</code>
     * @return The sourceKind.
     */
    @java.lang.Override
    public java.lang.String getSourceKind() {
      return instance.getSourceKind();
    }
    /**
     * <code>string source_kind = 3;</code>
     * @return The bytes for sourceKind.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceKindBytes() {
      return instance.getSourceKindBytes();
    }
    /**
     * <code>string source_kind = 3;</code>
     * @param value The sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKind(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceKind(value);
      return this;
    }
    /**
     * <code>string source_kind = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceKind() {
      copyOnWrite();
      instance.clearSourceKind();
      return this;
    }
    /**
     * <code>string source_kind = 3;</code>
     * @param value The bytes for sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKindBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceKindBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.OpenAudioStream)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.OpenAudioStream();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "sourceId_",
            "displayName_",
            "sourceKind_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.OpenAudioStream> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.OpenAudioStream.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.OpenAudioStream>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.OpenAudioStream)
  private static final io.listensphere.protocol.v1.OpenAudioStream DEFAULT_INSTANCE;
  static {
    OpenAudioStream defaultInstance = new OpenAudioStream();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OpenAudioStream.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.OpenAudioStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OpenAudioStream> PARSER;

  public static com.google.protobuf.Parser<OpenAudioStream> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

