// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface PairRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.PairRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   * @return The sender.
   */
  io.listensphere.protocol.v1.DeviceIdentity getSender();

  /**
   * <code>bytes sender_nonce = 2;</code>
   * @return The senderNonce.
   */
  com.google.protobuf.ByteString getSenderNonce();

  /**
   * <code>string one_time_code = 3;</code>
   * @return The oneTimeCode.
   */
  java.lang.String getOneTimeCode();
  /**
   * <code>string one_time_code = 3;</code>
   * @return The bytes for oneTimeCode.
   */
  com.google.protobuf.ByteString
      getOneTimeCodeBytes();
}
