// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface PairResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.PairResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>bytes controller_nonce = 2;</code>
   * @return The controllerNonce.
   */
  com.google.protobuf.ByteString getControllerNonce();

  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.listensphere.protocol.v1.ErrorCode error = 3;</code>
   * @return The error.
   */
  io.listensphere.protocol.v1.ErrorCode getError();

  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 4;</code>
   * @return Whether the controller field is set.
   */
  boolean hasController();
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity controller = 4;</code>
   * @return The controller.
   */
  io.listensphere.protocol.v1.DeviceIdentity getController();
}
