// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.PairRequest}
 */
public  final class PairRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PairRequest, PairRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.PairRequest)
    PairRequestOrBuilder {
  private PairRequest() {
    senderNonce_ = com.google.protobuf.ByteString.EMPTY;
    oneTimeCode_ = "";
  }
  private int bitField0_;
  public static final int SENDER_FIELD_NUMBER = 1;
  private io.listensphere.protocol.v1.DeviceIdentity sender_;
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   */
  @java.lang.Override
  public boolean hasSender() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   */
  @java.lang.Override
  public io.listensphere.protocol.v1.DeviceIdentity getSender() {
    return sender_ == null ? io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance() : sender_;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   */
  private void setSender(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  sender_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSender(io.listensphere.protocol.v1.DeviceIdentity value) {
    value.getClass();
  if (sender_ != null &&
        sender_ != io.listensphere.protocol.v1.DeviceIdentity.getDefaultInstance()) {
      sender_ =
        io.listensphere.protocol.v1.DeviceIdentity.newBuilder(sender_).mergeFrom(value).buildPartial();
    } else {
      sender_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
   */
  private void clearSender() {  sender_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int SENDER_NONCE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString senderNonce_;
  /**
   * <code>bytes sender_nonce = 2;</code>
   * @return The senderNonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSenderNonce() {
    return senderNonce_;
  }
  /**
   * <code>bytes sender_nonce = 2;</code>
   * @param value The senderNonce to set.
   */
  private void setSenderNonce(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    senderNonce_ = value;
  }
  /**
   * <code>bytes sender_nonce = 2;</code>
   */
  private void clearSenderNonce() {

    senderNonce_ = getDefaultInstance().getSenderNonce();
  }

  public static final int ONE_TIME_CODE_FIELD_NUMBER = 3;
  private java.lang.String oneTimeCode_;
  /**
   * <code>string one_time_code = 3;</code>
   * @return The oneTimeCode.
   */
  @java.lang.Override
  public java.lang.String getOneTimeCode() {
    return oneTimeCode_;
  }
  /**
   * <code>string one_time_code = 3;</code>
   * @return The bytes for oneTimeCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOneTimeCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(oneTimeCode_);
  }
  /**
   * <code>string one_time_code = 3;</code>
   * @param value The oneTimeCode to set.
   */
  private void setOneTimeCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    oneTimeCode_ = value;
  }
  /**
   * <code>string one_time_code = 3;</code>
   */
  private void clearOneTimeCode() {

    oneTimeCode_ = getDefaultInstance().getOneTimeCode();
  }
  /**
   * <code>string one_time_code = 3;</code>
   * @param value The bytes for oneTimeCode to set.
   */
  private void setOneTimeCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    oneTimeCode_ = value.toStringUtf8();

  }

  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.PairRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.PairRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.PairRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.PairRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.PairRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.PairRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.PairRequest)
      io.listensphere.protocol.v1.PairRequestOrBuilder {
    // Construct using io.listensphere.protocol.v1.PairRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    @java.lang.Override
    public boolean hasSender() {
      return instance.hasSender();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    @java.lang.Override
    public io.listensphere.protocol.v1.DeviceIdentity getSender() {
      return instance.getSender();
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    public Builder setSender(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.setSender(value);
      return this;
      }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    public Builder setSender(
        io.listensphere.protocol.v1.DeviceIdentity.Builder builderForValue) {
      copyOnWrite();
      instance.setSender(builderForValue.build());
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    public Builder mergeSender(io.listensphere.protocol.v1.DeviceIdentity value) {
      copyOnWrite();
      instance.mergeSender(value);
      return this;
    }
    /**
     * <code>.listensphere.protocol.v1.DeviceIdentity sender = 1;</code>
     */
    public Builder clearSender() {  copyOnWrite();
      instance.clearSender();
      return this;
    }

    /**
     * <code>bytes sender_nonce = 2;</code>
     * @return The senderNonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSenderNonce() {
      return instance.getSenderNonce();
    }
    /**
     * <code>bytes sender_nonce = 2;</code>
     * @param value The senderNonce to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderNonce(value);
      return this;
    }
    /**
     * <code>bytes sender_nonce = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderNonce() {
      copyOnWrite();
      instance.clearSenderNonce();
      return this;
    }

    /**
     * <code>string one_time_code = 3;</code>
     * @return The oneTimeCode.
     */
    @java.lang.Override
    public java.lang.String getOneTimeCode() {
      return instance.getOneTimeCode();
    }
    /**
     * <code>string one_time_code = 3;</code>
     * @return The bytes for oneTimeCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOneTimeCodeBytes() {
      return instance.getOneTimeCodeBytes();
    }
    /**
     * <code>string one_time_code = 3;</code>
     * @param value The oneTimeCode to set.
     * @return This builder for chaining.
     */
    public Builder setOneTimeCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setOneTimeCode(value);
      return this;
    }
    /**
     * <code>string one_time_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneTimeCode() {
      copyOnWrite();
      instance.clearOneTimeCode();
      return this;
    }
    /**
     * <code>string one_time_code = 3;</code>
     * @param value The bytes for oneTimeCode to set.
     * @return This builder for chaining.
     */
    public Builder setOneTimeCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOneTimeCodeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.PairRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.PairRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "sender_",
            "senderNonce_",
            "oneTimeCode_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\n\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.PairRequest> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.PairRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.PairRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.PairRequest)
  private static final io.listensphere.protocol.v1.PairRequest DEFAULT_INSTANCE;
  static {
    PairRequest defaultInstance = new PairRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PairRequest.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.PairRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PairRequest> PARSER;

  public static com.google.protobuf.Parser<PairRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

