// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.ProtocolVersion}
 */
public  final class ProtocolVersion extends
    com.google.protobuf.GeneratedMessageLite<
        ProtocolVersion, ProtocolVersion.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.ProtocolVersion)
    ProtocolVersionOrBuilder {
  private ProtocolVersion() {
  }
  public static final int MAJOR_FIELD_NUMBER = 1;
  private int major_;
  /**
   * <code>uint32 major = 1;</code>
   * @return The major.
   */
  @java.lang.Override
  public int getMajor() {
    return major_;
  }
  /**
   * <code>uint32 major = 1;</code>
   * @param value The major to set.
   */
  private void setMajor(int value) {
    
    major_ = value;
  }
  /**
   * <code>uint32 major = 1;</code>
   */
  private void clearMajor() {

    major_ = 0;
  }

  public static final int MINOR_FIELD_NUMBER = 2;
  private int minor_;
  /**
   * <code>uint32 minor = 2;</code>
   * @return The minor.
   */
  @java.lang.Override
  public int getMinor() {
    return minor_;
  }
  /**
   * <code>uint32 minor = 2;</code>
   * @param value The minor to set.
   */
  private void setMinor(int value) {
    
    minor_ = value;
  }
  /**
   * <code>uint32 minor = 2;</code>
   */
  private void clearMinor() {

    minor_ = 0;
  }

  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.ProtocolVersion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.ProtocolVersion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.ProtocolVersion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.ProtocolVersion prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.ProtocolVersion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.ProtocolVersion, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.ProtocolVersion)
      io.listensphere.protocol.v1.ProtocolVersionOrBuilder {
    // Construct using io.listensphere.protocol.v1.ProtocolVersion.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 major = 1;</code>
     * @return The major.
     */
    @java.lang.Override
    public int getMajor() {
      return instance.getMajor();
    }
    /**
     * <code>uint32 major = 1;</code>
     * @param value The major to set.
     * @return This builder for chaining.
     */
    public Builder setMajor(int value) {
      copyOnWrite();
      instance.setMajor(value);
      return this;
    }
    /**
     * <code>uint32 major = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMajor() {
      copyOnWrite();
      instance.clearMajor();
      return this;
    }

    /**
     * <code>uint32 minor = 2;</code>
     * @return The minor.
     */
    @java.lang.Override
    public int getMinor() {
      return instance.getMinor();
    }
    /**
     * <code>uint32 minor = 2;</code>
     * @param value The minor to set.
     * @return This builder for chaining.
     */
    public Builder setMinor(int value) {
      copyOnWrite();
      instance.setMinor(value);
      return this;
    }
    /**
     * <code>uint32 minor = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinor() {
      copyOnWrite();
      instance.clearMinor();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.ProtocolVersion)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.ProtocolVersion();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "major_",
            "minor_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.ProtocolVersion> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.ProtocolVersion.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.ProtocolVersion>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.ProtocolVersion)
  private static final io.listensphere.protocol.v1.ProtocolVersion DEFAULT_INSTANCE;
  static {
    ProtocolVersion defaultInstance = new ProtocolVersion();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProtocolVersion.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.ProtocolVersion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProtocolVersion> PARSER;

  public static com.google.protobuf.Parser<ProtocolVersion> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

