// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface ProtocolVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.ProtocolVersion)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 major = 1;</code>
   * @return The major.
   */
  int getMajor();

  /**
   * <code>uint32 minor = 2;</code>
   * @return The minor.
   */
  int getMinor();
}
