// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

/**
 * Protobuf type {@code listensphere.protocol.v1.StartStream}
 */
public  final class StartStream extends
    com.google.protobuf.GeneratedMessageLite<
        StartStream, StartStream.Builder> implements
    // @@protoc_insertion_point(message_implements:listensphere.protocol.v1.StartStream)
    StartStreamOrBuilder {
  private StartStream() {
    sessionId_ = com.google.protobuf.ByteString.EMPTY;
    sessionKey_ = com.google.protobuf.ByteString.EMPTY;
    sessionSalt_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int STREAM_ID_FIELD_NUMBER = 1;
  private int streamId_;
  /**
   * <code>fixed32 stream_id = 1;</code>
   * @return The streamId.
   */
  @java.lang.Override
  public int getStreamId() {
    return streamId_;
  }
  /**
   * <code>fixed32 stream_id = 1;</code>
   * @param value The streamId to set.
   */
  private void setStreamId(int value) {
    
    streamId_ = value;
  }
  /**
   * <code>fixed32 stream_id = 1;</code>
   */
  private void clearStreamId() {

    streamId_ = 0;
  }

  public static final int CODEC_FIELD_NUMBER = 2;
  private int codec_;
  /**
   * <code>uint32 codec = 2;</code>
   * @return The codec.
   */
  @java.lang.Override
  public int getCodec() {
    return codec_;
  }
  /**
   * <code>uint32 codec = 2;</code>
   * @param value The codec to set.
   */
  private void setCodec(int value) {
    
    codec_ = value;
  }
  /**
   * <code>uint32 codec = 2;</code>
   */
  private void clearCodec() {

    codec_ = 0;
  }

  public static final int SAMPLE_RATE_FIELD_NUMBER = 3;
  private int sampleRate_;
  /**
   * <code>uint32 sample_rate = 3;</code>
   * @return The sampleRate.
   */
  @java.lang.Override
  public int getSampleRate() {
    return sampleRate_;
  }
  /**
   * <code>uint32 sample_rate = 3;</code>
   * @param value The sampleRate to set.
   */
  private void setSampleRate(int value) {
    
    sampleRate_ = value;
  }
  /**
   * <code>uint32 sample_rate = 3;</code>
   */
  private void clearSampleRate() {

    sampleRate_ = 0;
  }

  public static final int CHANNEL_COUNT_FIELD_NUMBER = 4;
  private int channelCount_;
  /**
   * <code>uint32 channel_count = 4;</code>
   * @return The channelCount.
   */
  @java.lang.Override
  public int getChannelCount() {
    return channelCount_;
  }
  /**
   * <code>uint32 channel_count = 4;</code>
   * @param value The channelCount to set.
   */
  private void setChannelCount(int value) {
    
    channelCount_ = value;
  }
  /**
   * <code>uint32 channel_count = 4;</code>
   */
  private void clearChannelCount() {

    channelCount_ = 0;
  }

  public static final int FRAME_DURATION_MS_FIELD_NUMBER = 5;
  private int frameDurationMs_;
  /**
   * <code>uint32 frame_duration_ms = 5;</code>
   * @return The frameDurationMs.
   */
  @java.lang.Override
  public int getFrameDurationMs() {
    return frameDurationMs_;
  }
  /**
   * <code>uint32 frame_duration_ms = 5;</code>
   * @param value The frameDurationMs to set.
   */
  private void setFrameDurationMs(int value) {
    
    frameDurationMs_ = value;
  }
  /**
   * <code>uint32 frame_duration_ms = 5;</code>
   */
  private void clearFrameDurationMs() {

    frameDurationMs_ = 0;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString sessionId_;
  /**
   * <code>bytes session_id = 6;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionId() {
    return sessionId_;
  }
  /**
   * <code>bytes session_id = 6;</code>
   * @param value The sessionId to set.
   */
  private void setSessionId(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sessionId_ = value;
  }
  /**
   * <code>bytes session_id = 6;</code>
   */
  private void clearSessionId() {

    sessionId_ = getDefaultInstance().getSessionId();
  }

  public static final int SESSION_KEY_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString sessionKey_;
  /**
   * <code>bytes session_key = 7;</code>
   * @return The sessionKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionKey() {
    return sessionKey_;
  }
  /**
   * <code>bytes session_key = 7;</code>
   * @param value The sessionKey to set.
   */
  private void setSessionKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sessionKey_ = value;
  }
  /**
   * <code>bytes session_key = 7;</code>
   */
  private void clearSessionKey() {

    sessionKey_ = getDefaultInstance().getSessionKey();
  }

  public static final int SESSION_SALT_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString sessionSalt_;
  /**
   * <code>bytes session_salt = 8;</code>
   * @return The sessionSalt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionSalt() {
    return sessionSalt_;
  }
  /**
   * <code>bytes session_salt = 8;</code>
   * @param value The sessionSalt to set.
   */
  private void setSessionSalt(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sessionSalt_ = value;
  }
  /**
   * <code>bytes session_salt = 8;</code>
   */
  private void clearSessionSalt() {

    sessionSalt_ = getDefaultInstance().getSessionSalt();
  }

  public static final int UDP_PORT_FIELD_NUMBER = 9;
  private int udpPort_;
  /**
   * <code>uint32 udp_port = 9;</code>
   * @return The udpPort.
   */
  @java.lang.Override
  public int getUdpPort() {
    return udpPort_;
  }
  /**
   * <code>uint32 udp_port = 9;</code>
   * @param value The udpPort to set.
   */
  private void setUdpPort(int value) {
    
    udpPort_ = value;
  }
  /**
   * <code>uint32 udp_port = 9;</code>
   */
  private void clearUdpPort() {

    udpPort_ = 0;
  }

  public static final int FRAME_SAMPLES_FIELD_NUMBER = 10;
  private int frameSamples_;
  /**
   * <code>uint32 frame_samples = 10;</code>
   * @return The frameSamples.
   */
  @java.lang.Override
  public int getFrameSamples() {
    return frameSamples_;
  }
  /**
   * <code>uint32 frame_samples = 10;</code>
   * @param value The frameSamples to set.
   */
  private void setFrameSamples(int value) {
    
    frameSamples_ = value;
  }
  /**
   * <code>uint32 frame_samples = 10;</code>
   */
  private void clearFrameSamples() {

    frameSamples_ = 0;
  }

  public static io.listensphere.protocol.v1.StartStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.listensphere.protocol.v1.StartStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.listensphere.protocol.v1.StartStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.listensphere.protocol.v1.StartStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.listensphere.protocol.v1.StartStream prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code listensphere.protocol.v1.StartStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.listensphere.protocol.v1.StartStream, Builder> implements
      // @@protoc_insertion_point(builder_implements:listensphere.protocol.v1.StartStream)
      io.listensphere.protocol.v1.StartStreamOrBuilder {
    // Construct using io.listensphere.protocol.v1.StartStream.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>fixed32 stream_id = 1;</code>
     * @return The streamId.
     */
    @java.lang.Override
    public int getStreamId() {
      return instance.getStreamId();
    }
    /**
     * <code>fixed32 stream_id = 1;</code>
     * @param value The streamId to set.
     * @return This builder for chaining.
     */
    public Builder setStreamId(int value) {
      copyOnWrite();
      instance.setStreamId(value);
      return this;
    }
    /**
     * <code>fixed32 stream_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamId() {
      copyOnWrite();
      instance.clearStreamId();
      return this;
    }

    /**
     * <code>uint32 codec = 2;</code>
     * @return The codec.
     */
    @java.lang.Override
    public int getCodec() {
      return instance.getCodec();
    }
    /**
     * <code>uint32 codec = 2;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(int value) {
      copyOnWrite();
      instance.setCodec(value);
      return this;
    }
    /**
     * <code>uint32 codec = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      copyOnWrite();
      instance.clearCodec();
      return this;
    }

    /**
     * <code>uint32 sample_rate = 3;</code>
     * @return The sampleRate.
     */
    @java.lang.Override
    public int getSampleRate() {
      return instance.getSampleRate();
    }
    /**
     * <code>uint32 sample_rate = 3;</code>
     * @param value The sampleRate to set.
     * @return This builder for chaining.
     */
    public Builder setSampleRate(int value) {
      copyOnWrite();
      instance.setSampleRate(value);
      return this;
    }
    /**
     * <code>uint32 sample_rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleRate() {
      copyOnWrite();
      instance.clearSampleRate();
      return this;
    }

    /**
     * <code>uint32 channel_count = 4;</code>
     * @return The channelCount.
     */
    @java.lang.Override
    public int getChannelCount() {
      return instance.getChannelCount();
    }
    /**
     * <code>uint32 channel_count = 4;</code>
     * @param value The channelCount to set.
     * @return This builder for chaining.
     */
    public Builder setChannelCount(int value) {
      copyOnWrite();
      instance.setChannelCount(value);
      return this;
    }
    /**
     * <code>uint32 channel_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelCount() {
      copyOnWrite();
      instance.clearChannelCount();
      return this;
    }

    /**
     * <code>uint32 frame_duration_ms = 5;</code>
     * @return The frameDurationMs.
     */
    @java.lang.Override
    public int getFrameDurationMs() {
      return instance.getFrameDurationMs();
    }
    /**
     * <code>uint32 frame_duration_ms = 5;</code>
     * @param value The frameDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setFrameDurationMs(int value) {
      copyOnWrite();
      instance.setFrameDurationMs(value);
      return this;
    }
    /**
     * <code>uint32 frame_duration_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameDurationMs() {
      copyOnWrite();
      instance.clearFrameDurationMs();
      return this;
    }

    /**
     * <code>bytes session_id = 6;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <code>bytes session_id = 6;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <code>bytes session_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }

    /**
     * <code>bytes session_key = 7;</code>
     * @return The sessionKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionKey() {
      return instance.getSessionKey();
    }
    /**
     * <code>bytes session_key = 7;</code>
     * @param value The sessionKey to set.
     * @return This builder for chaining.
     */
    public Builder setSessionKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionKey(value);
      return this;
    }
    /**
     * <code>bytes session_key = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionKey() {
      copyOnWrite();
      instance.clearSessionKey();
      return this;
    }

    /**
     * <code>bytes session_salt = 8;</code>
     * @return The sessionSalt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionSalt() {
      return instance.getSessionSalt();
    }
    /**
     * <code>bytes session_salt = 8;</code>
     * @param value The sessionSalt to set.
     * @return This builder for chaining.
     */
    public Builder setSessionSalt(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionSalt(value);
      return this;
    }
    /**
     * <code>bytes session_salt = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionSalt() {
      copyOnWrite();
      instance.clearSessionSalt();
      return this;
    }

    /**
     * <code>uint32 udp_port = 9;</code>
     * @return The udpPort.
     */
    @java.lang.Override
    public int getUdpPort() {
      return instance.getUdpPort();
    }
    /**
     * <code>uint32 udp_port = 9;</code>
     * @param value The udpPort to set.
     * @return This builder for chaining.
     */
    public Builder setUdpPort(int value) {
      copyOnWrite();
      instance.setUdpPort(value);
      return this;
    }
    /**
     * <code>uint32 udp_port = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpPort() {
      copyOnWrite();
      instance.clearUdpPort();
      return this;
    }

    /**
     * <code>uint32 frame_samples = 10;</code>
     * @return The frameSamples.
     */
    @java.lang.Override
    public int getFrameSamples() {
      return instance.getFrameSamples();
    }
    /**
     * <code>uint32 frame_samples = 10;</code>
     * @param value The frameSamples to set.
     * @return This builder for chaining.
     */
    public Builder setFrameSamples(int value) {
      copyOnWrite();
      instance.setFrameSamples(value);
      return this;
    }
    /**
     * <code>uint32 frame_samples = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameSamples() {
      copyOnWrite();
      instance.clearFrameSamples();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:listensphere.protocol.v1.StartStream)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.listensphere.protocol.v1.StartStream();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "streamId_",
            "codec_",
            "sampleRate_",
            "channelCount_",
            "frameDurationMs_",
            "sessionId_",
            "sessionKey_",
            "sessionSalt_",
            "udpPort_",
            "frameSamples_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0006\u0002\u000b\u0003\u000b" +
              "\u0004\u000b\u0005\u000b\u0006\n\u0007\n\b\n\t\u000b\n\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.listensphere.protocol.v1.StartStream> parser = PARSER;
        if (parser == null) {
          synchronized (io.listensphere.protocol.v1.StartStream.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.listensphere.protocol.v1.StartStream>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:listensphere.protocol.v1.StartStream)
  private static final io.listensphere.protocol.v1.StartStream DEFAULT_INSTANCE;
  static {
    StartStream defaultInstance = new StartStream();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StartStream.class, defaultInstance);
  }

  public static io.listensphere.protocol.v1.StartStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StartStream> PARSER;

  public static com.google.protobuf.Parser<StartStream> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

