// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listensphere/v1/control.proto

// Protobuf Java Version: 3.25.3
package io.listensphere.protocol.v1;

public interface StartStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:listensphere.protocol.v1.StartStream)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>fixed32 stream_id = 1;</code>
   * @return The streamId.
   */
  int getStreamId();

  /**
   * <code>uint32 codec = 2;</code>
   * @return The codec.
   */
  int getCodec();

  /**
   * <code>uint32 sample_rate = 3;</code>
   * @return The sampleRate.
   */
  int getSampleRate();

  /**
   * <code>uint32 channel_count = 4;</code>
   * @return The channelCount.
   */
  int getChannelCount();

  /**
   * <code>uint32 frame_duration_ms = 5;</code>
   * @return The frameDurationMs.
   */
  int getFrameDurationMs();

  /**
   * <code>bytes session_id = 6;</code>
   * @return The sessionId.
   */
  com.google.protobuf.ByteString getSessionId();

  /**
   * <code>bytes session_key = 7;</code>
   * @return The sessionKey.
   */
  com.google.protobuf.ByteString getSessionKey();

  /**
   * <code>bytes session_salt = 8;</code>
   * @return The sessionSalt.
   */
  com.google.protobuf.ByteString getSessionSalt();

  /**
   * <code>uint32 udp_port = 9;</code>
   * @return The udpPort.
   */
  int getUdpPort();

  /**
   * <code>uint32 frame_samples = 10;</code>
   * @return The frameSamples.
   */
  int getFrameSamples();
}
